on: [push, workflow_dispatch]
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ftp.davidevaleriani.it
        username: me@davidevaleriani.it
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/
