on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp://ftp.davidevaleriani.it/public_html
        username: me@davidevaleriani.it
        password: ${{ secrets.FTP_PASSWORD }}
